const CARS = {
    "mercedes-g-wagon": {
        name: "Mercedes G-Wagon",
        img: "assets/car_left.png",
        meta: "V8 AMG | obsidian black",
        price: "₦185,000,000",
        power: "585hp",
        torque: "850Nm",
        speed: "4.5s",
        topSpeed: "220km/h",
        engine: "V8",
        details: {
            manufacturer: "Mercedes-AMG GmbH",
            year: "2023",
            production: "1979 – Present",
            limited: "Standard Production",
            engineFull: "4.0L V8 Biturbo AMG",
            zeroToSixty: "4.2s (0–60 mph)",
            zeroToHundred: "4.5s (0–100 km/h)",
            seating: "5 Passengers",
            cargo: "688 L",
            leather: "AMG Nappa Leather",
            heatedSeats: "Yes — Front & Rear",
            stereo: "Burmester® 3D Surround (13 speakers)",
            headlights: "Multibeam LED with Cornering Light",
            ai: "Active Brake Assist, Active Lane Keeping Assist, DISTRONIC Distance Assist",
            funFact: "Originally engineered as a military vehicle for the Shah of Iran in 1979. Over 400,000 units sold — and the boxy silhouette has never changed."
        }
    },
    "lexus-lx-600": {
        name: "Lexus LX 600",
        img: "assets/car_right.png",
        meta: "Elite Luxury | sonic quartz",
        price: "₦160,000,000",
        power: "409hp",
        torque: "650Nm",
        speed: "6.9s",
        topSpeed: "210km/h",
        engine: "V6",
        details: {
            manufacturer: "Lexus — Toyota Motor Corporation",
            year: "2022",
            production: "1996 – Present",
            limited: "Ultra Luxury Trim (Limited Run)",
            engineFull: "3.5L V6 Twin-Turbo",
            zeroToSixty: "6.7s (0–60 mph)",
            zeroToHundred: "6.9s (0–100 km/h)",
            seating: "7 Passengers",
            cargo: "242 L (behind 3rd row)",
            leather: "Semi-Aniline Leather",
            heatedSeats: "Yes — All Rows",
            stereo: "Mark Levinson® Reference Surround (25 speakers, 2,400W)",
            headlights: "Triple-Beam LED with Adaptive Lighting",
            ai: "Lexus Safety System+ 3.0, Pre-Collision System, Lane Departure Alert, Radar Cruise Control",
            funFact: "Shares its GA-F platform with the Toyota Land Cruiser 300, but receives over 200 exclusive Lexus-only engineering refinements unavailable on any other vehicle."
        }
    },
    "range-rover": {
        name: "Range Rover",
        img: "assets/car_left_2.png",
        meta: "Autobiography | carpathian grey",
        price: "₦145,000,000",
        power: "523hp",
        torque: "750Nm",
        speed: "4.6s",
        topSpeed: "250km/h",
        engine: "V8",
        details: {
            manufacturer: "Land Rover — Jaguar Land Rover",
            year: "2023",
            production: "1970 – Present",
            limited: "SV Edition One (Special Vehicle)",
            engineFull: "4.4L V8 Twin-Turbo BMW",
            zeroToSixty: "4.4s (0–60 mph)",
            zeroToHundred: "4.6s (0–100 km/h)",
            seating: "5 Passengers (7 Optional)",
            cargo: "818 L",
            leather: "Perlino & Windsor Semi-Aniline",
            heatedSeats: "Yes — All Seats + Massage",
            stereo: "Meridian Signature Reference (35 speakers, 1,600W)",
            headlights: "Pixel LED with Adaptive Driving Beam",
            ai: "Terrain Response 2, ClearSight Ground View, Active Noise Cancellation, Head-Up Display",
            funFact: "In 1970, a Range Rover was exhibited inside the Louvre in Paris — the only automobile ever displayed as a work of art in the museum."
        }
    },
    "escalade-v": {
        name: "Escalade V",
        img: "assets/car_right_2.png",
        meta: "supercharged | raven black",
        price: "₦195,000,000",
        power: "682hp",
        torque: "885Nm",
        speed: "4.4s",
        topSpeed: "200km/h",
        engine: "V8",
        details: {
            manufacturer: "Cadillac — General Motors",
            year: "2023",
            production: "1999 – Present",
            limited: "V-Series Performance Variant",
            engineFull: "6.2L Supercharged V8 (LT4)",
            zeroToSixty: "4.3s (0–60 mph)",
            zeroToHundred: "4.4s (0–100 km/h)",
            seating: "7 Passengers",
            cargo: "722 L",
            leather: "Semi-Aniline Leather with Suede Inserts",
            heatedSeats: "Yes — Front & Rear, Ventilated + Massage",
            stereo: "AKG Studio Reference (36 speakers, 1,000W)",
            headlights: "Curved OLED Signature with HD Surround Vision",
            ai: "Super Cruise® Hands-Free Driving (400,000+ miles), Night Vision Camera, Rear Camera Mirror",
            funFact: "Super Cruise is the world's first true hands-free driver assistance system for the highway — it uses LiDAR map data, not just cameras."
        }
    },
    "elite-suv": {
        name: "Elite SUV",
        img: "assets/car_left.png",
        meta: "AMG | matte black",
        price: "₦165,000,000",
        power: "450hp",
        torque: "700Nm",
        speed: "5.1s",
        topSpeed: "210km/h",
        engine: "V6"
    },
    "luxury-lx": {
        name: "Luxury LX",
        img: "assets/car_right.png",
        meta: "Ultra Luxury | arctic white",
        price: "₦150,000,000",
        power: "380hp",
        torque: "600Nm",
        speed: "7.2s",
        topSpeed: "205km/h",
        engine: "V6"
    }
};
