if (!window.CARS) {
var CARS = {
    "mercedes-g-wagon": {
        name: "Mercedes-Benz G-Wagon",
        img: "assets/car_left.png",
        price: "₦180,000,000",
        power: "585hp",
        topSpeed: "220km/h",
        torque: "850nm",
        logo: "assets/brands/mercedes.png",
        brand: "Mercedes-Benz",
        type: "SUV",
        category: "LUXURY",
        energy: "PETROL",
        mileage: 1200,
        details: {
            manufacturer: "Mercedes-Benz",
            year: "2024",
            production: "Graz, Austria",
            limited: "SOP Standard",
            zeroToSixty: "4.4s",
            zeroToHundred: "4.5s",
            engineFull: "4.0L V8 Biturbo",
            seating: "5 Adults",
            cargo: "621 Liters",
            leather: "Nappa Leather",
            heatedSeats: "Front & Rear",
            stereo: "Burmester Surround",
            headlights: "Multibeam LED",
            ai: "Distronic Plus",
            funFact: "The G-Wagon was originally developed as a military vehicle in the 1970s."
        }
    },
    "lexus-lx-600": {
        name: "Lexus LX 600",
        img: "assets/car_right.png",
        price: "₦165,000,000",
        power: "409hp",
        topSpeed: "210km/h",
        torque: "650nm",
        logo: "assets/brands/lexus.png",
        brand: "Lexus",
        type: "SUV",
        category: "LUXURY",
        energy: "PETROL",
        mileage: 50,
        details: {
            manufacturer: "Lexus",
            year: "2024",
            production: "Yoshiwara, Japan",
            limited: "VIP Grade",
            zeroToSixty: "6.8s",
            zeroToHundred: "6.9s",
            engineFull: "3.4L V6 Twin-Turbo",
            seating: "4/7 Adults",
            cargo: "1,274 Liters",
            leather: "Semi-Aniline",
            heatedSeats: "Climate Concierge",
            stereo: "Mark Levinson 25-Spk",
            headlights: "Triple-Beam LED",
            ai: "Lexus Safety System+ 2.5",
            funFact: "The LX 600 features an active height control system with 4 settings."
        }
    },
    "range-rover": {
        name: "Range Rover Autobiography",
        img: "assets/2024RangeRover.png",
        price: "₦195,000,000",
        power: "523hp",
        topSpeed: "250km/h",
        torque: "750nm",
        logo: "assets/brands/landrover.png",
        brand: "Land Rover",
        type: "SUV",
        category: "ADVENTURE",
        energy: "PETROL",
        mileage: 15,
        details: {
            manufacturer: "Land Rover",
            year: "2024",
            production: "Solihull, UK",
            limited: "Autobiography",
            zeroToSixty: "4.5s",
            zeroToHundred: "4.6s",
            engineFull: "4.4L V8 Twin-Turbo",
            seating: "5 Adults",
            cargo: "818 Liters",
            leather: "SV Bespoke Leather",
            heatedSeats: "Hot Stone Massage",
            stereo: "Meridian Signature",
            headlights: "Digital LED w/ Projection",
            ai: "ClearSight Ground View",
            funFact: "The new Range Rover can wade through water up to 900mm deep."
        }
    },
    "escalade-v": {
        name: "Cadillac Escalade V",
        img: "assets/escalade2025.png",
        price: "₦210,000,000",
        power: "682hp",
        topSpeed: "200km/h",
        torque: "885nm",
        logo: "assets/brands/cadillac.png",
        brand: "Cadillac",
        type: "SUV",
        category: "SPORT",
        energy: "PETROL",
        mileage: 120,
        details: {
            manufacturer: "Cadillac",
            year: "2024",
            production: "Arlington, USA",
            limited: "V-Series Performance",
            zeroToSixty: "4.3s",
            zeroToHundred: "4.4s",
            engineFull: "6.2L Supercharged V8",
            seating: "7 Adults",
            cargo: "722 Liters",
            leather: "Full Semi-Aniline",
            heatedSeats: "Active Lumbar Msd",
            stereo: "AKG Studio Reference 36-Spk",
            headlights: "LED Vertical Blades",
            ai: "Super Cruise Hands-Free",
            funFact: "The Escalade-V is the most powerful full-size SUV in the industry."
        }
    },
    "_2026cadillac": {
        name: "Cadillac Escalade IQ",
        img: "assets/_2026cadillac.png",
        price: "₦240,000,000",
        power: "750hp",
        topSpeed: "180km/h",
        torque: "1064nm",
        logo: "assets/brands/cadillac.png",
        brand: "Cadillac",
        type: "SUV",
        category: "LUXURY",
        energy: "ELECTRIC",
        mileage: 5,
        details: {
            manufacturer: "Cadillac",
            year: "2026",
            production: "Factory ZERO, USA",
            limited: "EV Luxury",
            zeroToSixty: "4.9s",
            zeroToHundred: "5.0s",
            engineFull: "Ultium Battery / Dual Motor",
            seating: "7 Adults",
            cargo: "670 Liters",
            leather: "Eco-Conscious Materials",
            heatedSeats: "Front & Mid Row",
            stereo: "AKG 40-Speaker",
            headlights: "Vertical Signature LED",
            ai: "Ultra Cruise",
            funFact: "The Escalade IQ features a massive 55-inch total diagonal pillar-to-pillar display."
        }
    },
    "byd-ato3": {
        name: "BYD Atto 3",
        img: "assets/byd-ato3.png",
        price: "₦45,000,000",
        power: "201hp",
        topSpeed: "160km/h",
        torque: "310nm",
        logo: "assets/brands/byd.png",
        brand: "BYD",
        type: "SUV",
        category: "ECONOMY",
        energy: "ELECTRIC",
        mileage: 2400,
        details: {
            manufacturer: "BYD",
            year: "2024",
            production: "Shenzhen, China",
            limited: "Extended Range",
            zeroToSixty: "7.2s",
            zeroToHundred: "7.3s",
            engineFull: "Electric / 60.48kWh Blade Battery",
            seating: "5 Adults",
            cargo: "440 Liters",
            leather: "Vegan Interior",
            heatedSeats: "Front Seats",
            stereo: "Dirac HD Sound",
            headlights: "Crystal LED",
            ai: "DiPilot",
            funFact: "BYD stands for 'Build Your Dreams'."
        }
    },
    "camry2025hybrid": {
        name: "Toyota Camry Hybrid",
        img: "assets/camry2025hybrid.png",
        price: "₦65,000,000",
        power: "225hp",
        topSpeed: "185km/h",
        torque: "221nm",
        logo: "assets/brands/toyota.png",
        brand: "Toyota",
        type: "SEDAN",
        category: "ECONOMY",
        energy: "HYBRID",
        mileage: 10,
        details: {
            manufacturer: "Toyota",
            year: "2025",
            production: "Georgetown, USA",
            limited: "XLE Grade",
            zeroToSixty: "7.4s",
            zeroToHundred: "7.5s",
            engineFull: "2.5L 4-Cylinder Hybrid",
            seating: "5 Adults",
            cargo: "428 Liters",
            leather: "Leather-Trimmed",
            heatedSeats: "Power-Adjustable",
            stereo: "JBL Premium Audio",
            headlights: "Bi-LED Multi-Feature",
            ai: "Toyota Safety Sense 3.0",
            funFact: "The 2025 Camry is the first to be offered exclusively as a hybrid in the US."
        }
    },
    "corolla2025": {
        name: "Toyota Corolla",
        img: "assets/corolla2025.png",
        price: "₦38,000,000",
        power: "169hp",
        topSpeed: "190km/h",
        torque: "205nm",
        logo: "assets/brands/toyota.png",
        brand: "Toyota",
        type: "SEDAN",
        category: "ECONOMY",
        energy: "PETROL",
        mileage: 1800,
        details: {
            manufacturer: "Toyota",
            year: "2025",
            production: "Blue Springs, USA",
            limited: "SE Dynamic",
            zeroToSixty: "8.2s",
            zeroToHundred: "8.3s",
            engineFull: "2.0L 4-Cylinder",
            seating: "5 Adults",
            cargo: "361 Liters",
            leather: "Fabric/SofTex Mix",
            heatedSeats: "Optional",
            stereo: "Toyota Multimedia",
            headlights: "LED Accent Lighting",
            ai: "Toyota Safety Sense",
            funFact: "The Corolla is the best-selling car nameplate in world history."
        }
    },
    "cybertruck": {
        name: "Tesla Cybertruck",
        img: "assets/cybertruck.png",
        price: "₦140,000,000",
        power: "845hp",
        topSpeed: "209km/h",
        torque: "10000nm",
        logo: "assets/brands/tesla.png",
        brand: "Tesla",
        type: "TRUCK",
        category: "OFF-ROAD",
        energy: "ELECTRIC",
        mileage: 3200,
        details: {
            manufacturer: "Tesla",
            year: "2024",
            production: "Giga Texas, USA",
            limited: "Cyberbeast",
            zeroToSixty: "2.6s",
            zeroToHundred: "2.7s",
            engineFull: "Tri-Motor AWD",
            seating: "5 Adults",
            cargo: "3,400 Liters (Total)",
            leather: "Cyber-Tech Synthetic",
            heatedSeats: "Full Interior",
            stereo: "15-Speaker Custom Audio",
            headlights: "Integrated Light Bar",
            ai: "Full Self-Driving Capability",
            funFact: "The Cybertruck's exoskeleton is made of Ultra-Hard 30X Cold-Rolled stainless steel."
        }
    },
    "kia2023sportage": {
        name: "Kia Sportage",
        img: "assets/kia2023sportage.png",
        price: "₦42,000,000",
        power: "187hp",
        topSpeed: "200km/h",
        torque: "241nm",
        logo: "assets/brands/kia.png",
        brand: "Kia",
        type: "SUV",
        category: "FAMILY",
        energy: "PETROL",
        mileage: 15600,
        details: {
            manufacturer: "Kia",
            year: "2023",
            production: "West Point, USA",
            limited: "X-Line",
            zeroToSixty: "8.6s",
            zeroToHundred: "8.7s",
            engineFull: "2.5L 4-Cylinder",
            seating: "5 Adults",
            cargo: "1,121 Liters",
            leather: "SynTex Trim",
            heatedSeats: "Front Bench",
            stereo: "Harman Kardon Premium",
            headlights: "LED Projector High-Beam",
            ai: "Kia Drive Wise",
            funFact: "The 2023 Sportage features a boomerang-shaped LED headlight design."
        }
    },
    "mercedes2025sclass": {
        name: "Mercedes-Benz S-Class",
        img: "assets/mercedes2025sclass.png",
        price: "₦255,000,000",
        power: "442hp",
        topSpeed: "250km/h",
        torque: "560nm",
        logo: "assets/brands/mercedes.png",
        brand: "Mercedes-Benz",
        type: "SEDAN",
        category: "LUXURY",
        energy: "HYBRID",
        mileage: 12,
        details: {
            manufacturer: "Mercedes-Benz",
            year: "2025",
            production: "Sindelfingen, Germany",
            limited: "S 580 Executive",
            zeroToSixty: "4.8s",
            zeroToHundred: "4.9s",
            engineFull: "4.0L V8 Biturbo w/ Mild Hybrid",
            seating: "5 Adults",
            cargo: "540 Liters",
            leather: "Exclusive Nappa",
            heatedSeats: "Energizing Comfort",
            stereo: "Burmester High-End 4D",
            headlights: "Digital Light",
            ai: "Level 3 Drive Pilot",
            funFact: "The S-Class has long been considered the 'World's Best Car' by industry critics."
        }
    }
};
window.CARS = CARS;

var BRANDS = [
    { name: "Rolls-Royce", logo: "assets/brands/rolls-royce.png" },
    { name: "Bentley", logo: "assets/brands/bentley.png" },
    { name: "Mercedes-Benz", logo: "assets/brands/mercedes.png" },
    { name: "BMW", logo: "assets/brands/bmw.png" },
    { name: "Audi", logo: "assets/brands/audi.png" },
    { name: "Lexus", logo: "assets/brands/lexus.png" },
    { name: "Land Rover", logo: "assets/brands/landrover.png" },
    { name: "Porsche", logo: "assets/brands/porsche.png" },
    { name: "Ferrari", logo: "assets/brands/ferrari.png" },
    { name: "Lamborghini", logo: "assets/brands/lamborghini.png" },
    { name: "McLaren", logo: "assets/brands/mclaren.png" },
    { name: "Aston Martin", logo: "assets/brands/aston-martin.png" },
    { name: "Bugatti", logo: "assets/brands/bugatti.png" },
    { name: "Tesla", logo: "assets/brands/tesla.png" },
    { name: "Cadillac", logo: "assets/brands/cadillac.png" },
    { name: "Toyota", logo: "assets/brands/toyota.png" },
    { name: "Honda", logo: "assets/brands/honda.png" },
    { name: "Ford", logo: "assets/brands/ford.png" },
    { name: "Chevrolet", logo: "assets/brands/chevrolet.png" },
    { name: "Volkswagen", logo: "assets/brands/volkswagen.png" }
];
window.BRANDS = BRANDS;
}

if (typeof module !== 'undefined') {
    module.exports = { CARS: window.CARS, BRANDS: window.BRANDS };
}
