if (!window.PAINT_HEX_MAP) {

const PAINT_HEX_MAP = {
    // Blacks
    'black':                             '#0e0e10',
    'jet black':                         '#0a0a0f',
    'obsidian black metallic':           '#1c1c1e',
    'magnetite black metallic':          '#1e1e24',
    'night black magno':                 '#151518',
    'carbon black metallic':             '#18181c',
    'black sapphire metallic':           '#1a1c28',
    'chromite black metallic':           '#1e1e20',
    'midnight black metallic':           '#14141a',
    'global black':                      '#0f0f10',
    'beluga':                            '#0d0d0e',
    'ebony black':                       '#131316',
    'onyx black':                        '#111116',
    'brilliant black':                   '#141414',
    'cosmos black':                      '#121214',
    'santorini black':                   '#161618',
    'santorini black metallic':          '#181818',
    'phantom black':                     '#121215',
    'noir':                              '#141416',
    'diamond black crystal pearlcoat':   '#1a1820',
    'black raven':                       '#0e0e12',
    'mythos black metallic':             '#181820',
    'ligurian black ultra metallic gloss': '#1c1c22',
    'tupelo black':                      '#161616',
    'satin abyss blue':                  '#1a2030',
    'incognito':                         '#1e1e22',
    'midnight sky':                      '#16182a',
    'satin dark grey':                   '#2a2a2e',
    'matte black':                       '#1a1a1c',
    'satin black':                       '#1e1e20',
    'black and dark grey':               '#181a1c',

    // Whites / Creams / Pearls
    'polar white':                       '#f0eeea',
    'white':                             '#f5f5f0',
    'alpine white':                      '#f2f0eb',
    'diamond white metallic':            '#e8e5e0',
    'moonlight white magno':             '#e6e5e2',
    'fuji white':                        '#f2f0ec',
    'arctic white':                      '#f0eee8',
    'pearl white':                       '#f4f2ee',
    'glacier white metallic':            '#eef0f0',
    'mineral white metallic':            '#ede9e4',
    'calcite white':                     '#f0ede8',
    'ostuni pearl white':                '#f0ede6',
    'ostuni pearl white metallic':       '#eeeae2',
    'crystal white tricoat':             '#f0f0ec',
    'bright white clearcoat':            '#f5f4f0',
    'carrara white':                     '#eeece6',
    'carrara white metallic':            '#eceae4',
    'grace white':                       '#f2efea',
    'icy white special effect':          '#eef0f2',
    'snow white pearl':                  '#f0eee8',
    'wind chill pearl':                  '#eef0ee',
    'eminent white pearl':               '#f0ede8',
    'platinum white':                    '#dedad4',
    'frozen pure grey metallic':         '#d4d2ce',
    'signature deep white':              '#f2f0ec',
    'g manufaktur platinum white':       '#dedad4',
    'satin ceramic white':               '#f0ede8',
    'ice cap':                           '#eef2f2',
    'glacial white pearl':               '#eeede8',
    'bmw individual frozen brilliant white': '#f0eee8',
    'chalk':                             '#dedad2',
    'seashell':                          '#f0e8dc',
    'adobe frost':                       '#e8dfd0',

    // Silvers / Greys / Platinums
    'selenite grey metallic':            '#7d8082',
    'selenite gray magno':               '#7a7d80',
    'mojave silver metallic':            '#aaadb0',
    'cirrus silver metallic':            '#c6c8c8',
    'iridium silver metallic':           '#9c9ea2',
    'palladium silver metallic':         '#b2b4b6',
    'steel grey metallic':               '#6c6f72',
    'graphite metallic':                 '#484c50',
    'monza gray magno':                  '#5a5d60',
    'nardo grey':                        '#8c9094',
    'dark graphite metallic':            '#3a3c40',
    'mineral silver metallic':           '#a4a6a8',
    'titanium silver metallic':          '#9a9d9f',
    'desert silver metallic':            '#c4bfb0',
    'florett silver metallic':           '#a8aaaa',
    'silver zynith':                     '#a6a8aa',
    'dolomite silver metallic':          '#b0b2b4',
    'silverstone ii':                    '#b4b6b8',
    'everlasting silver':                '#c0c2c2',
    'atomic silver':                     '#b8babb',
    'celestial silver metallic':         '#b2b4b6',
    'hakuba silver':                     '#c8cacc',
    'hakuba silver metallic':            '#c4c6c8',
    'classic silver metallic':           '#a8aaa8',
    'celestite gray metallic':           '#8a8e92',
    'shadow metallic':                   '#747678',
    'fluid silver metallic':             '#b8bab8',
    'eiger grey':                        '#7a7c80',
    'eiger grey metallic':               '#787c80',
    'quartzite grey metallic':           '#8e9092',
    'arctic grey':                       '#9294a0',
    'anthracite':                        '#3e4044',
    'slate grey':                        '#5e6268',
    'dark grey':                         '#484c50',
    'slate':                             '#5a5e62',
    'charcoal':                          '#404448',
    'dravit grey metallic':              '#5c5e64',
    'scivaro grey':                      '#828690',
    'carpathian grey':                   '#5e6268',
    'carpathian grey premium metallic':  '#606470',
    'charente grey':                     '#7c8086',
    'charente grey premium metallic':    '#7e828a',
    'typhoon grey':                      '#6a6e74',
    'cashmere gray':                     '#a4a29a',
    'rotor gray':                        '#606266',
    'wolf gray':                         '#9a9ea6',
    'boulder grey':                      '#9ea2a8',
    'boulder':                           '#a0a4aa',
    'burnout grey':                      '#7a7e84',
    'predawn gray mica':                 '#5a5e64',
    'harbour grey':                      '#7c8086',
    'fog':                               '#c4c6c8',
    'river rock':                        '#a4a8a4',
    'gravity gray':                      '#8e9298',
    'galactic gray metallic':            '#909498',
    'celestite':                         '#8c9096',
    'signature graphite metallic':       '#505458',
    'g manufaktur titanium grey pearl':  '#9098a0',
    'brookyn grey metallic':             '#7a7e84',
    'brooklyn grey metallic':            '#7a7e84',
    'bmw individual dravit grey metallic':'#5c5e64',
    'frozen grey':                       '#9ea2a8',
    'urban grey metallic':               '#8a8e92',
    'agate grey metallic':               '#8e9296',
    'samurai gray metallic':             '#9e9c98',
    'deep space metallic':               '#606870',
    'flight grey':                       '#9ea2a8',
    'storm bay tricoat':                 '#5a6268',
    'smoke white and light grey cashmere': '#d8d4cc',
    'sheer gray with dark medium cinder accents': '#8e9298',
    'galactic gray':                     '#8e9298',

    // Blues
    'china blue':                        '#1c3a5c',
    'mystic blue metallic':              '#1e3050',
    'twilight blue metallic':            '#2a4060',
    'brilliant blue metallic':           '#1e4a8a',
    'sea blue metallic':                 '#1a506a',
    'south sea blue metallic':           '#0e3855',
    'galaxy blue metallic':              '#1c2e58',
    'dark moon blue metallic':           '#1a2840',
    'lunar blue metallic':               '#1c2e4a',
    'montego blue metallic':             '#18304e',
    'marina bay blue metallic':          '#2040a0',
    'tanzanite blue metallic':           '#1a2860',
    'tanzanite blue ii metallic':        '#1c2c64',
    'moonlight blue metallic':           '#202e50',
    'varesine blue metallic':            '#1e3060',
    'portofino blue':                    '#1c3a58',
    'algarve blue metallic':             '#183064',
    'ascari blue':                       '#2040b0',
    'imperial blue':                     '#1a2860',
    'navy blue':                         '#1a2a48',
    'fleet blue':                        '#1e3460',
    'reservoir blue':                    '#1e3454',
    'blue agave':                        '#1c3a5a',
    'atlantic blue metallic':            '#0e3060',
    'salamanca blue':                    '#1c3660',
    'surf blue':                         '#1e4868',
    'signature mystic blue metallic':    '#1e3050',
    'g manufaktur midnight blue':        '#1a2840',
    'g manufaktur yacht blue':           '#1e3a5c',
    'yacht blue':                        '#1e3a5c',
    'signature yacht blue':              '#1e3a5c',
    'muscari blue':                      '#2a3480',
    'blueprint':                         '#1c3058',
    'blue gray':                         '#485870',
    'portobello':                        '#3c4a5e',
    'g manufaktur china blue':           '#1c3a5c',

    // Greens
    'cumbrian green':                    '#2a4030',
    'lake green':                        '#244830',
    'jungle green':                      '#243e20',
    'dark emerald metallic':             '#1a4028',
    'belgravia green':                   '#2a4230',
    'belgravia green metallic':          '#2a4232',
    'british racing green':              '#1c3c22',
    'british racing green ultra metallic gloss': '#1c4024',
    'isle of man green metallic':        '#2a5a30',
    'pine green':                        '#264830',
    'nori green pearl':                  '#303e28',
    'tactical green':                    '#3a4830',
    'forest green':                      '#2a4a28',
    'dark olive green magno':            '#3c4826',
    'olive metallic':                    '#5a6030',
    'g manufaktur dark olive green magno':'#3c4826',
    'green hell magno':                  '#2c4a1c',
    'emerald green metallic':            '#1a6b3c',
    'bmw individual signal green':       '#28a050',
    'signal green':                      '#28a050',

    // Reds / Crimsons / Maroons
    'cardinal red magno':                '#7a1515',
    'cardinal red metallic':             '#8b1a1a',
    'manufaktur cardinal red metallic':  '#8b1a1a',
    'infrared tintcoat':                 '#c41a1a',
    'carmine red':                       '#8e1a1a',
    'ruby flare pearl':                  '#7a1010',
    'arras red':                         '#9a1818',
    'aventurin red metallic':            '#8c1c1c',
    'bengal red':                        '#a01c1c',
    'chilli red':                        '#b81a1a',
    'ardent red':                        '#a01818',
    'toronto red metallic':              '#962020',
    'barcelona red metallic':            '#8a1c1c',
    'radiant red tintcoat':              '#b82020',
    'velvet red pearlcoat':              '#6e1414',
    'satin crimson red':                 '#8a1414',
    'supersonic red':                    '#c01818',
    'volcano red':                       '#aa1e1e',
    'cricket ball':                      '#a02020',
    'g manufaktur bengal red':           '#a01c1c',
    'g manufaktur jupiter red':          '#a81c1c',
    'dawning red':                       '#9a1c1c',
    'black cherry tintcoat':             '#401020',
    'satin rose gold':                   '#cc8878',
    'roseleaf':                          '#c07060',
    'blushing pink':                     '#e8a0a0',
    'iridescent purple':                 '#602080',
    'amethyst grey-purple ultra metallic gloss': '#7060a0',
    'ametrin metallic':                  '#806090',
    'purple silk':                       '#6040a0',
    'purple':                            '#502090',

    // Golds / Bronzes / Browns / Coppers
    'kalahari gold magno':               '#c6a244',
    'sintered bronze magno':             '#8a6838',
    'dakota brown magno':                '#5a3826',
    'copper orange magno':               '#b85c20',
    'batumi gold':                       '#b89440',
    'batumi gold premium metallic':      '#b89440',
    'sakhir gold metallic':              '#b09038',
    'sakhir orange':                     '#c06020',
    'lantau bronze':                     '#886040',
    'mahogany metallic':                 '#602a1a',
    'tobacco brown':                     '#5a3820',
    'dark auburn':                       '#50201a',
    'cashmere beige metallic':           '#c4b896',
    'vicuna beige metallic':             '#c4b896',
    'sandstone':                         '#c8b890',
    'sandstone metallic':                '#c0b088',
    'ember gold pearlcoat':              '#c09838',
    'beech brown':                       '#604830',
    'havana':                            '#704030',
    'taruma brown':                      '#6a3e24',
    'morocco brown':                     '#4a3020',
    'okapi brown':                       '#5c3c28',
    'cacao':                             '#3e2010',
    'espresso brown':                    '#3e2018',
    'g manufaktur espresso brown':       '#3e2018',
    'g manufaktur saddle brown':         '#6a3a20',
    'saddle brown':                      '#6a3a20',
    'g manufaktur sintered bronze magno':'#8a6838',
    'g manufaktur dakota brown magno':   '#5a3826',
    'kona brown':                        '#5c3820',
    'burnt oak':                         '#7c4c28',
    'moccasin':                          '#c8a880',
    'casden tan':                        '#c0a878',
    'maple sugar':                       '#c8a060',
    'palomino':                          '#c0a070',
    'sandy sicilian metallic':           '#c0b078',
    'signature kalahari gold magno':     '#c6a244',
    'signature truffle brown':           '#7a5840',
    'signature nut brown':               '#8a5a30',

    // Oranges / Yellows
    'dragon orange metallic':            '#c44c14',
    'sanguinello orange ultra metallic gloss': '#d05c14',
    'sunrise copper ultra metallic gloss': '#c86030',
    'sunset gold ultra metallic gloss':  '#d09030',
    'corn yellow':                       '#e8c840',
    'sunflare':                          '#e4c030',
    'tuscan sun':                        '#d09040',
    'signature pastel yellow':           '#e8d880',
    'tumeric':                           '#c8a020',

    // Special / Ultra Metallic Gloss (Rolls-Royce Bespoke, etc.)
    'ionian silver ultra metallic gloss': '#b8bab8',
    'flux silver ultra metallic gloss':  '#a0a4a8',
    'ethereal frost silver ultra metallic gloss': '#c0c4c8',
    'velocity blue ultra metallic gloss': '#1e50a0',
    'constellation blue ultra metallic gloss': '#18406a',
    'petrolix blue ultra metallic gloss': '#1a3460',
    'tourmaline brown ultra metallic gloss': '#7a5038',
    'ligurian black':                    '#1c1c22',
    'aquamarine blue metallic':          '#1a6080',

    // Misc / Duo-tone
    'heavy metal':                       '#606468',
    'underground':                       '#4a4e52',
    'tactical gray':                     '#707478',
    'tactical grey':                     '#707478',
    'linen':                             '#ddd4c0',
    'portland':                          '#8c9298',
    'camel':                             '#c09060',
    'tan':                               '#c09060',
    'saddle':                            '#a06030',
    'whisper beige':                     '#ddd4c0',
    'atlas beige':                       '#c8bc98',
    'atlas beige metallic':              '#c4bc98',
    'pearl beige':                       '#e0d8c0',
    'ice edge':                          '#e8f0f0',
    'daytona gray pearl effect':         '#606468',
    'signature silicon gray':            '#8a9098',
    'g manufaktur arabian gray':         '#8e9298',
    'manganese luster':                  '#a0a8b0',
    'bmw individual daytona violet metallic': '#5a3870',
    'bmw individual grigio telesto pearl metallic': '#909098',
    'bmw individual verde ermes metallic': '#2a6040',
    'frozen black':                      '#181818',
    'bmw individual frozen black':       '#181818',
    'gravity gray metallic':             '#8e9298',
    'typhoon grey metallic':             '#6e7278',
    'moonstone':                         '#c8c6be',
    'platinum magno':                    '#d0cec8',
    'g manufaktur desert silver metallic': '#c4bfb0',
    'signature desert silver metallic':  '#c4bfb0',
    'magnus metal frost':                '#9ea2a8',
    'sedona sauvage':                    '#9a7060',
    'armagnac':                          '#7a4030',
    'damson':                            '#4a1828',
    'nightfall mica':                    '#2a2040',
    'surf blue metallic':                '#1e4068',
    'indus silver metallic':             '#a8aaac',
    'slip grey':                         '#8a8e94',
    'satin slip grey':                   '#8a8e94',
    'rudy flare pearl':                  '#7a1010',
    'lunar blue':                        '#1c2e4a',
    'cashmere beige':                    '#c8bc98',
    'warm silver':                       '#b4b6b4',
    'sand dune metallic':                '#c0b898',
    'g manufaktur arabain gray':         '#8e9298',
    'blue + black':                      '#1a2848',
    'blue + grey':                       '#304860',
    'white + blue':                      '#d0dce8',
    'sea salt and black':                '#c0c8c4',
    'black, full merino':                '#181818',
    'backen black with santorini accents': '#1a1a1c',
    'copper tinted clear':               '#c07840',
    'bmw individual macadamia':          '#d0c0a0',
};

function _paintNameToHex(name) {
    if (!name || typeof name !== 'string') return null;
    const skip = /\band\b|\bbespoke\b|\bcustom\b|\bmade to measure\b|\bmatch to sample\b|\bpaint to sample\b|\b\d+\+\b|\bmulliner\b|\bcommission\b/i;
    if (skip.test(name)) return null;
    const key = name.toLowerCase().trim();
    if (PAINT_HEX_MAP[key]) return PAINT_HEX_MAP[key];
    const stripped = key
        .replace(/^(manufaktur|designo|individual|signature|g manufaktur|bmw individual|satin|frozen)\s+/i, '')
        .trim();
    return PAINT_HEX_MAP[stripped] || null;
}

window.PAINT_HEX_MAP = PAINT_HEX_MAP;
window._paintNameToHex = _paintNameToHex;

}
